config/routes.rb
MhtAppV2::Application.routes.draw do
resources :care_groups do
    member do
      get 'manage'
    end
  end

resources :patients do
  collection do 
    post 'data'
    match 'search' => 'patients#search', via: [:get, :post], as: :search
  end 
end

devise_for :users

resources :dashboard do
  collection do 
    get 'patient'
  end 
end
  root  'static_pages#home'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/users/sign_up', to: 'devise/registrations#new', via: 'get'
  match '/profile', to: 'devise/registrations#edit', via: 'get'

  match '/users/sign_in', to: 'devise/sessions#new', via: 'get'
  
  

end

app/models/care_group.rb
class CareGroup < ActiveRecord::Base
	belongs_to :patients
	belongs_to :users
end

app/controllers/care_groups_controller.rb
class CareGroupsController < ApplicationController
  before_action :set_care_group, only: [:show, :edit, :update, :destroy, :manage]

  # GET /care_groups
  # GET /care_groups.json
  def index
    @care_groups = CareGroup.all
  end

  # GET /care_groups/1
  # GET /care_groups/1.json
  def show
  end

  # GET /care_groups/new
  def new
    @care_group = CareGroup.new
  end

  # GET /care_groups/1/edit
  def edit
  end

  def manage
    @patients = CareGroup.find(params[:id]).patients
  end

  # POST /care_groups
  # POST /care_groups.json
  def create
    @care_group = CareGroup.new(care_group_params)

    respond_to do |format|
      if @care_group.save
        format.html { redirect_to @care_group, notice: 'Care group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @care_group }
      else
        format.html { render action: 'new' }
        format.json { render json: @care_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /care_groups/1
  # PATCH/PUT /care_groups/1.json
  def update
    respond_to do |format|
      if @care_group.update(care_group_params)
        format.html { redirect_to @care_group, notice: 'Care group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @care_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /care_groups/1
  # DELETE /care_groups/1.json
  def destroy
    @care_group.destroy
    respond_to do |format|
      format.html { redirect_to care_groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_care_group
      @care_group = CareGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def care_group_params
      params.require(:care_group).permit(:name)
    end
end

app/helpers/care_groups_helper.rb
module CareGroupsHelper
end

app/views/care_groups/_form.html.erb
<div class="container">
<%= form_for(@care_group) do |f| %>
  <% if @care_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@care_group.errors.count, "error") %> prohibited this care_group from being saved:</h2>

      <ul>
      <% @care_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <form class="form-horizontal " role="form">
    <div class="jumbotron p-and-cg">
    <fieldset>
      <legend class="text-center"> <%= yield (:title)%></legend> 
      <div class="form-group">
        <%= f.label :name, :class => 'col-lg-2 control-label' %>
        <div class="col-lg-10">
          <%= f.text_field :name, :class =>'input form-control'  %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit :class => 'btn btn-small btn-primary' %>
        </div>
      </div>
    </fieldset>
    </div>
  </form>

<% end %>
</div>

app/views/care_groups/edit.html.erb
<% provide(:title, 'Edit Care Group') %>

<div class="container">
	<div class="row">
		<%= render 'form' %>
		<div class="links"><%= link_to 'Show', @care_group %> | <%= link_to 'Back', care_groups_path %></div>
	</div>
</div> 

app/views/care_groups/index.html.erb
<% provide(:title, 'Listing All Care Groups') %>
<div class="container sidebar-adjust">
  <h1 class="header table-header" >Listing care groups</h1>
  <div class="row">
   
      <table class="table table-responsive text-hover">
        <thead>
          <tr class="danger">
            <th>Name</th>
            <th>Actions</th>
          </tr>
          </thead>

        <tbody>
          <% @care_groups.each do |care_group| %>
            <tr>
              <td><%= care_group.name %></td>
              <td><a><%= link_to 'Show', care_group %> | <%= link_to 'Edit', edit_care_group_path(care_group) %> | <%= link_to 'Manage Members', manage_care_group_path(care_group) %> | <%= link_to 'Destroy', care_group, method: :delete, data: { confirm: 'Are you sure?' } %></a></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row">
      <%= link_to 'New Care group', new_care_group_path %>
    </div>
</div>

app/views/care_groups/manage.html.erb
<% provide(:title, 'Manage' + " " + @care_group.name + " " + 'Care group members' )%>
<h1>Manage Care Group Members</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

  <% @patient.all.find_each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/care_groups/new.html.erb
<% provide(:title, 'New Care Group') %>

<div class="container">
	<div class="row">
		<%= render 'form' %>
		<div class="links"><%= link_to 'Back', care_groups_path %></div>
	</div>
</div> 

app/views/care_groups/show.html.erb
<% provide(:title, 'Care Group:' + " " + @care_group.name )%>
<div class="container">
  <h1 class="header table-header" ><%= @care_group.name %></h1>
  <p id="notice"><%= notice %></p>
  <div class="row">
    <table class="table table-striped table-hover sidebar-adjust">
      <thead>
        <tr class="success">
        	<th>Name:</th>
        	<th>Actions:</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @care_group.name %></td>
          <td><%= link_to 'Edit', edit_care_group_path(@care_group) %></td>
      	</tr>
  	  </tbody>
  	</table>
  </div>
  <div class="row">
	<%= link_to 'Back', care_groups_path %>
  </div>
</div>