config/routes.rb
MhtAppV2::Application.routes.draw do
resources :care_groups do
    member do
      get 'manage'
    end
  end

resources :patients do
  collection do 
    post 'data'
    match 'search' => 'patients#search', via: [:get, :post], as: :search
  end 
end

devise_for :users

resources :dashboard do
  collection do 
    get 'patient'
  end 
end
  root  'static_pages#home'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/users/sign_up', to: 'devise/registrations#new', via: 'get'
  match '/profile', to: 'devise/registrations#edit', via: 'get'

  match '/users/sign_in', to: 'devise/sessions#new', via: 'get'
  
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
before_filter :authenticate_user!
 
def index
end


def patient
end

end

app/helpers/dashboard_helper.rb
module DashboardHelper

def current_user?(user)
  user == current_user
end

end

app/views/dashboard/index.html.erb
<% provide(:title, 'Critical Care Dashboard') %>

  <div class="row" id="row-top">
    <div class="col-md-12">
        <h2 class="text-center">Mindful Health Dashboard Overview</h2>
        <h4 class="header">Care team on staff: 4</h4>
        <div class="progress progress-striped active">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="40"
            aria-valuemin="0" aria-valuemax="100" style="width: 40%">
            <span class="sr-only">40% Complete (success)</span>
          </div>
        </div>

        <h4>Green patients: 8</h4>
        <div class="progress progress-striped active">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
          aria-valuemin="0" aria-valuemax="100" style="width: 80%">
          <span class="sr-only">20% Complete</span>
        </div>
      </div>
      
      <h4>Cautionary patients: 6</h4>    
      <div class="progress progress-striped active">
        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60"
          aria-valuemin="0" aria-valuemax="100" style="width: 60%">
          <span class="sr-only">60% Complete (warning)</span>
        </div>
      </div>

      <h4>Critical patients: 2</h4>
      <div class="progress progress-striped active">
        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80"
          aria-valuemin="0" aria-valuemax="100" style="width: 20%">
          <span class="sr-only">80% Complete</span>
        </div>
      </div>
    </div>
  </div>
  
  <div class ="row">
    <div class="col-md-6 col-sm-4 col-xs-3">
      <div class="jumbotron text-center dbjumbo">
        <h2>Manage Patients</h2>
        <p>Add patients, remove exsisting patients, and more.</p>
        <div class="links"><%= link_to "Manage Patients", patients_path, :class => 'btn btn-lg btn-primary' %></div>
      </div>
    </div>
    <div class="col-md-6 col-sm-4 col-xs-3">
      <div class="jumbotron text-center dbjumbo">
        <h2>Manage Care Team</h2>
        <p>Configure care team memberships and profiles.</p>
        <div class="links"><%= link_to "Manage Care Team", care_groups_path, :class => 'btn btn-lg btn-primary' %></div>
      </div>
    </div>
  </div>

  <div class= "row">
    <div class="col-md-4 col-sm-4">
      <div class="well well-sm text-center welldb">
        <b>Recent user activity</b>
        <div class="row">
          <a href="#" class="btn btn-xs btn-info">Review Activity</a>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-4">
      <div class="well well-sm text-center welldb">
        <b>Physician on staff: Dr. Robertson</b>
        <div class="row">
          <a href="#" class="btn btn-xs btn-info">Contact Now</a>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-4">
      <div class="well well-sm text-center welldb">
        <b>Questions? Contact Mindful Health</b>
        <div class="row">
          <a><%= link_to "Contact Us", contact_path, :class => 'btn btn-xs btn-info' %></a>
        </div>
      </div>
    </div>
  
</div>