config/routes.rb
MhtAppV2::Application.routes.draw do
resources :care_groups do
    member do
      get 'manage'
    end
  end

resources :patients do
  collection do 
    post 'data'
    match 'search' => 'patients#search', via: [:get, :post], as: :search
  end 
end

devise_for :users

resources :dashboard do
  collection do 
    get 'patient'
  end 
end
  root  'static_pages#home'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/users/sign_up', to: 'devise/registrations#new', via: 'get'
  match '/profile', to: 'devise/registrations#edit', via: 'get'

  match '/users/sign_in', to: 'devise/sessions#new', via: 'get'
  
  

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :care_group
	has_many :patient_data
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :disable_sidebar, only: [:index]
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  # before_action :send_threshold_email
  layout 'application', :except => [:index]
  # GET /patients
  # GET /patients.json
  def disable_sidebar 
    @disable_sidebar = true
  end
  def search
    index
    render :index
  end
  
  def index
    @patients = Patient.all
    @search = Patient.search(params[:q])
    @patients = @search.result
    
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @patient }
      else
        format.html { render action: 'new' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update

    respond_to do |format|
    if @patient.update(patient_params) 
        #curPat = Patient.find(params[:id])
        #@curData = PatientData.find(params[:id])
       #@patientNum = 50
       
      #if @patient.vitalThreshold > @patientNum 

        
          #ThresholdMailer.notification_email(current_user).deliver 
          #redirect_to :controller => 'patient', :action => 'show', :notice => 'Patient spo2 values are low!' 
          #format.html { redirect_to @patient, notice: 'Patient spo2 values are low!'}
          #format.json { head :no_content }
      #end
        
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }

      else
        format.html { render action: 'edit' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end

  def data
      @mode = params[:mode]
      
      @data = PatientData.where(:patient_id => params[:patient_id]).order(transmission_time: :asc).limit(96)

      if(@mode == "1 week")
        @data = PatientData.where(:patient_id => params[:patient_id]).order(transmission_time: :asc).limit(672)
      end
      
      respond_to do |format|
        format.json { render json: @data}
      end
  end


def send_threshold_email
  #if Patient.vitalThreshold > @patient_data.spo2
  #@curPat = Patient.find(params[:id])
  #@curPat = Patient.find_by :patient_id 1
  #@curData = PatientData.find(params[:id])
  #@curData = PatientData.where(:patient_id => params[:patient_id])
  #@user = User.find_by :id 1
  #@currentID = 1
  #@curData = PatientData.find_by :patient_id @currentID
  #if @curData.spo2 < @curPat.vitalThreshold
    #ThresholdMailer.notification_email(current_user.email).deliver 
    #redirect_to :controller => 'patient', :action => 'show', :notice => 'Patient spo2 values are low!' 
  #end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :email, :phone, :condition, :deviceId, :vitalThreshold)
    end

    #def patient_data_params
    #  params.require(:patient).permit(:patient_id)
    #end

    
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>
      <ul>
        <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <form class="form-horizontal" role="form">
      <div class="jumbotron p-and-cg">
      <fieldset>
        <legend class="text-center">  <%= yield (:title)%> </legend> 

      <div class="form-group">
        <%= f.label :name, :class => 'col-lg-2 control-label' %>
        <div class="col-lg-10">
          <%= f.text_field :name, :class =>'input form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, :class => 'col-lg-2 control-label'  %>
        <div class="col-lg-10">
          <%= f.text_field :email, :class => 'input form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :phone, :class => 'col-lg-2 control-label'  %>
        <div class="col-lg-10">
          <%= f.text_field :phone, :class => 'input form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :condition, :class => 'col-lg-2 control-label'  %>
        <div class="col-lg-10">
          <%= f.text_area :condition, :class => 'input form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :deviceId, :class => 'col-lg-2 control-label'  %>
        <div class="col-lg-10">
          <%= f.number_field :deviceId, :class => 'input form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :vitalThreshold, :class => 'col-lg-2 control-label'  %>
        <div class="col-lg-10">
          <%= f.number_field(:vitalThreshold, :class => 'input form-control', in: 1..100, step: 1)%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit "Submit", :class => 'btn btn-small btn-primary' %>
        </div>
      </div>
    </fieldset>
    </div>
  </form>

<% end %>

app/views/patients/edit.html.erb
<% provide(:title, 'Edit:' + " " + @patient.name) %>
<div class="container">

	<%= render 'form' %>

	<div class="links"><%= link_to 'Show', @patient %> | <%= link_to 'Back', patients_path %></div>
</div>

app/views/patients/index.html.erb
<% provide(:title, 'Patient Index') %>
<div class="container" id= "index-patient-page" style = "margin-left: -18%">
  <div class="inset">
  <h1 class="header table-header text-center" >Listing patients</h1>
  
  <%= search_form_for @search, url: search_patients_path, html: { method: :post }, :class => 'form-inline' do |f| %>
    <div class = "form-group" >
      <%=f.label :name_cont, "Name contains:", :class => 'control-label' %>
      <%= f.text_field :name_cont, :class => 'input form-control' %>
    </div>
    <div class="form-group"><%= f.submit "Search", :class => 'btn btn-small btn-success'%></div>
  <%end%>


  <div class="row">
      <table class="table table-responsive text-hover">
        <thead>
          <tr class="info">
            <th><%= sort_link(@search, :name, "Name") %></th>
            <th><%= sort_link(@search, :email, "Email") %></th>
            <th><%= sort_link(@search, :phone, "Phone Number") %></th>
            <th>Condition</th>
            <th><%= sort_link(@search, :deviceId, "Device ID") %></th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @patients.each do |patient| %>
          <tr>
            <td><%= patient.name %></td>
            <td><%= patient.email %></td>
            <td><%= patient.phone %></td>
            <td><%= patient.condition %></td>
            <td><%= patient.deviceId %></td>
            <td><%= patient.vitalThreshold %></td>
            <td><a><%= link_to 'Show', patient %></a> | <a><%= link_to 'Edit', edit_patient_path(patient) %></a> | <a><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></a> </td>
          </tr>
     
        <% end %>
      </tbody>
    </table>

    <div class = "row">
      <%= link_to 'Back to Search', patients_path %>
    </div>
        <div class="row">
     <%= link_to 'New Patient', new_patient_path %>
    </div>

  </div>


 </div>
</div>

app/views/patients/new.html.erb
<% provide(:title, 'New Patient') %>


	<%= render 'form' %>

	<div class="links"><%= link_to 'Back', patients_path %></div>


<!--<div class="container">
<footer class="footer">
  <nav>
    <ul>
      
    </ul>
  </nav>
</footer>
</div>-->

app/views/patients/show.html.erb
<% provide(:title, @patient.name + "patient page") %>
<div class="sidebar-adjust">
  <h1 class="header table-header" ><%= @patient.name %></h1>
  
  <div class="row">
    <table class="table table-striped table-hover" id="patient_table">
      <thead>
        <tr class="success">
          <th>Name:</th>
          <th>Email:</th>
          <th>Phone:</th>
          <th>Condition:</th>
          <th>Device ID:</th>
          <th>Vital Threshold:</th>
          <th>Actions:</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @patient.name %></td>
          <td><%= @patient.email %></td>
          <td><%= @patient.phone %></td>
          <td><%= @patient.condition %></td>
          <td><%= @patient.deviceId %></td>
          <td><%= @patient.vitalThreshold %></td>
          <td><%= link_to 'Edit', edit_patient_path(@patient) %></td>
        </tr>
      </tbody>
    </table>
  </div>

 <!-- end of table-->

  <div class="patient-metrics">
    
      <div class="row ">
        <h4><u>Patient Metrics</u></h4>
        <span class="graph-btns">
          <button type="button" class="btn btn-primary" id="btnAutoRefresh">Auto Refresh</button>
          <button  type="button" class="btn btn-primary" id="24hr_data">24 Hours</button>
          <button  type="button" class="btn btn-primary" id="1wk_data">1 Week</button>
        </span>
      </div>
      <div class="row">
        <div class="demo-container">
          <div id="graph_legend"></div>
          <div id="placeholder" style="width:700px;height:375px;" class="demo-placeholder"></div>
        </div>
      </div>  
   
  </div>
      <div class="row">
      <%= link_to 'Back', patients_path %>
    </div> 
</div>