config/routes.rb
MhtAppV2::Application.routes.draw do
resources :care_groups do
    member do
      get 'manage'
    end
  end

resources :patients do
  collection do 
    post 'data'
    match 'search' => 'patients#search', via: [:get, :post], as: :search
  end 
end

devise_for :users

resources :dashboard do
  collection do 
    get 'patient'
  end 
end
  root  'static_pages#home'

  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/users/sign_up', to: 'devise/registrations#new', via: 'get'
  match '/profile', to: 'devise/registrations#edit', via: 'get'

  match '/users/sign_in', to: 'devise/sessions#new', via: 'get'
  
  

end

app/views/layouts/_footer.html.erb
  <% if user_signed_in? %>
  <footer class="footer pull-right">
  	<nav>
  		 Signed in as <%= current_user.email %>  &nbsp <%= link_to "Contact  ",  contact_path %>
   		
   	</nav>
   </footer>
  <% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a><%= link_to "Mindful Health", root_path, id: "logo" %></a>
		</div>
		<ul class="nav navbar-nav navbar-right">

			<% if user_signed_in? %> 
                <li><%= link_to "Profile", edit_user_registration_path %></li>
                <li><%= link_to "Settings", '#'%></li> <!-- what types of settings do we need?-->
				<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %><li>
			
			<% else %>
				<li><%= link_to "Meet the Team", about_path %></li>
				<li><%= link_to "Login", new_user_session_path %></li>
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
			<% end %>
			<li><%= link_to "Home", root_path, id: "home_link" %></li>
		</ul>
	</div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <button type="button" data-dismiss="alert" class="close">×</button>
     
      
         <a> <%= value %> </a>
    
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->

<div class="well sidebar-nav"id="sidebar-wrapper">
  <ul class="nav" id="side-nav">
  	<h4 class="row text-left">Patient Managment</h4>
  		<div class="row text-left" id="patient_names"> 
  			<% Patient.all.find_each do |patient| %>
      		<li><a><%= link_to patient.name , patient_path(patient) %></a></li>
      		<% end %>
      	</div>  
  </ul>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script> 
  <script src="http://d23cj0cdvyoxg0.cloudfront.net/xivelyjs-1.0.4.min.js"></script>  
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header'  %>  

	<% if user_signed_in? %>
		<%= render 'layouts/sidebar' unless @disable_sidebar %>
			<div class="container page-content-wrapper">
				<%= render 'layouts/messages' %>
				<%= yield %>
				<%= render 'layouts/footer' %>
			</div>
						

		
	<% else %>
	<div class= "container error-messages-wrapper">
		<%= render 'layouts/messages' %>
	</div>

		<%=yield %>
	

		
	<% end %>
     	
</body>
</html>